### ISSUE TITLE
Error triggered when there is no error

### ISSUE THREAD

**Issue by Nicosoft** [zoom/zoom-lib-node#1]
Hi,

I am building multiple scripts in NodesJS that query ZoomUS.
To start I am using the service 'user/getbyemail'.

The error is triggered as you can see in the screenshot but the call was successful based on the log.
So I don't understand why the error is triggered.
Am I doing something wrong?

Thanks

```javascript
var zoomconfig = {
  key : '<mykey>',
  secret : '<mysecret>',
  email: '<email@email.com>'
}

// Include the zoom library 
var Zoom = require("zoomus")({
    "key" : zoomconfig.key,
    "secret" : zoomconfig.secret
});

var params = {
  email: zoomconfig.email
}

Zoom.user.getByEmail(params, function (err, res) {
  if(err) {
    console.log('ERROR', err);
  } else {
    var user = JSON.parse(res);
    console.log('user', user);
    }
});
```

Result:
![untitled-2](https://user-images.githubusercontent.com/4625910/29350137-82382636-82a0-11e7-90af-a4eac887c26e.png)

**Comment by joshuawoodward** [comment]
For some reason the readme is not updated on the npm site. The callback function is not  function(err, res){} just function (res){}

See https://zoom.github.io/api/?javascript#get-user-by-email-address-and-login-type
